### ISSUE TITLE
Tracking release 0.0.9

### ISSUE THREAD

**Issue by oscartbeaumont** [specta-rs/specta#1]
Development:
 - [x] Export comments from Rust
 - [x] [automatically_derived](https://doc.rust-lang.org/reference/attributes/derive.html#the-automatically_derived-attribute) on proc macros output
 - [x] `tokio::sync::*` types added to Specta
 - [x] #7
 - [x] #19 
 - [x] #9
 - [x] #11
 - [x] #10
 - [x] #12

Release:
 - [x] Merge specta from rspc back into specta
 - [x] Make Specta repo public
 - [ ] Corresponding rspc release
 - [ ] Corresponding PCR release
